### ISSUE TITLE
[Enhancements]about the palyer

### ISSUE THREAD

**Issue by cooblog** [Ani-Moopa/Moopa#100]
## What is the feature you'd like?

I would like to integrate the episode selector into the player

## Why do you think this feature would be useful?

I like that, I think it's more neat and beautiful

**Comment by DevanAbinaya** [comment]
sure, I'll add this later

**Comment by cooblog** [comment]
> sure, I'll add this later

Thank you. Looking forward to it.

**Comment by DevanAbinaya** [comment]
hopefully soon
