### ISSUE TITLE
[Bug] Source provider list of episodes being redirected incorrectly.

### ISSUE THREAD

**Issue by kiki7766** [Ani-Moopa/Moopa#105]
**Describe the bug**
When accessing to this anime [Mahoutsukai no Yome SEASON 2 Part 2](https://moopa.live/en/anime/166452) seems that the Source Provider comes from [Zoro](https://zorox.to/) (I will assume that is from this site) and has the same title of the episodes as [Mahoutsukai no Yome SEASON 2 - Zoro Provider](https://zorox.to/watch/mahoutsukai-no-yome-season-2-4q2p7/).

**To Reproduce**
1. Go to [Mahoutsukai no Yome SEASON 2 Part 2](https://moopa.live/en/anime/166452)
2. Compare titles with [Zoro Provider](https://zorox.to/watch/mahoutsukai-no-yome-season-2-4q2p7/)
3. Compare videos from [Mahoutsukai no Yome SEASON 2](https://moopa.live/en/anime/154364) with [Mahoutsukai no Yome SEASON 2 Part 2](https://moopa.live/en/anime/166452) in which has the same content the only difference is that comes from different source provider.
4. Usually, the source from [Mahoutsukai no Yome SEASON 2 Part 2](https://moopa.live/en/anime/166452) comes from [GogoAnime.tv](http://gogoanime.tv/) but for me GogoAnime seems to be having issues presenting the episodes, so using the [Zoro Site - Mahoutsukai no Yome SEASON 2 Part 2](https://zorox.to/watch/mahoutsukai-no-yome-season-2-part-2-4qw0j) seems to be working just fine.

**Expected behavior**
New releases episodes from [Zoro Site with the correct redirect](https://zorox.to/watch/mahoutsukai-no-yome-season-2-part-2-4qw0j), hopefully this is a minor bug.
Currently, this anime should have only 8 episodes. 

**Screenshots**
Mahoutsukai no Yome SEASON 2 Part 2
![image](https://github.com/Ani-Moopa/Moopa/assets/19612515/6586584d-1c7d-41cd-be64-781eafcd48ad)
Same Titles as **Mahoutsukai no Yome SEASON 2**
![image](https://github.com/Ani-Moopa/Moopa/assets/19612515/ad36e12e-3b82-4e6a-aa13-23fc8b30b888)
In which should be only 8 episodes 
![image](https://github.com/Ani-Moopa/Moopa/assets/19612515/cd89bff5-dad9-4020-aa62-0b0467b4f090)

 

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 119.0.6045.160 (Official Build) (64-bit)

**Smartphone (please complete the following information):**
 - Device: N/A
 - OS: N/A
 - Browser N/A
 - Version N/A

**Additional context**
Hope that this anime is the only one with this issue, but if there something I could do to contribute or help this amazing Webapp, please let me know.

**Possible Solution**
Perhaps whenever a source provider is down/slow or have any issues redirect to the next source provider that Moopa supports/uses. Thank you! 🫡

**Comment by kiki7766** [comment]
Just to update this issue. Seems that is back to normal episodes releases but only for the GogoAnime Source ... If I select from Zoro Source the redirect issue persists. 

- [Moopa Site - Anime](https://moopa.live/en/anime/166452) - If I select the GogoAnime Source the episodes appears correctly (9 episodes 🥳) 
- For some reason selecting the Zoro Source still redirects incorrectly to the previous season. 😭

**Comment by Artrix9095** [comment]
closing for now because this seems to be fixed
