### ISSUE TITLE
help. An error occurred on client. ???

### ISSUE THREAD

**Issue by Naiml007** [Ani-Moopa/Moopa#106]
![Screenshot 2023-12-01 064336](https://github.com/Ani-Moopa/Moopa/assets/90306726/c98434f2-8a7f-4e79-8bfb-7616c9c54801)

**Comment by Naiml007** [comment]
https://ani-moopa-five.vercel.app/en

**Comment by Su4o** [comment]
It's just because you tried doing requests on the webpage too fast, for example, clicking an anime, clicking an episode, clicking the episode title, selecting dub, now you get an error page. 

But, if this happens all the time, I don't really know anymore.
