### ISSUE TITLE
[Bug] Source not found

### ISSUE THREAD

**Issue by Genxster1998** [Ani-Moopa/Moopa#109]
**Describe the bug**

**To Reproduce**
1. Go to 'moopa.live'
2. Click on 'HxH any episode using either Gogoanime or Animepahe source'
3. Source not found error popup 

**Expected behavior**

**Screenshots**

![IMG_0320](https://github.com/Ani-Moopa/Moopa/assets/23246830/6543c9c0-d40a-438e-8fca-4cfa6ead9ead)

**iPad:**
 - OS: iPadOS
 - Browser [ safari]
 - Version [17.0]

**Additional context**

**Possible Solution**
If you have any ideas on how to solve the issue, please describe them here.

**Comment by Artrix9095** [comment]
could you send a screenshot of your console?

**Comment by DevanAbinaya** [comment]
Animepahe is working for me.

https://moopa.live/en/anime/watch/11061/animepahe?id=5017-163&num=1

**Comment by Genxster1998** [comment]
It's odd , Gogoanime still not working but somehow animepahe started working right now, I swear , I have tried like 3,4 times for both sources after going through issues as nobody reported it earlier. I have attached SS already , it quickly fallback from player screen to that screen .

**Comment by DevanAbinaya** [comment]
yes there was an issue with animepahe, but it's resolved now
