### ISSUE TITLE
failed netlify Deploy

### ISSUE THREAD

**Issue by Naiml007** [Ani-Moopa/Moopa#119]
![Screenshot 2024-01-27 234538](https://github.com/Ani-Moopa/Moopa/assets/90306726/4a5893a1-b98c-4a37-baa8-c934a7ee50b3)

10:55:25 PM: build-image version: fcb0c1b3ada6d25c1cb58e8bc514f5f23cc14f15 (focal)
10:55:25 PM: buildbot version: d4068f75b500fda01f8eb2592656f157c0c28aa7
10:55:26 PM: Fetching cached dependencies
10:55:26 PM: Failed to fetch cache, continuing with build
10:55:26 PM: Starting to prepare the repo for build
10:55:26 PM: No cached dependencies found. Cloning fresh repo
10:55:26 PM: git clone --filter=blob:none https://github.com/Naiml007/Ani-Moopa
10:55:26 PM: Preparing Git Reference refs/heads/main
10:55:28 PM: Starting to install dependencies
10:55:28 PM: Python version set to 3.8
10:55:28 PM: Attempting Ruby version 2.7.2, read from environment
10:55:28 PM: Using Ruby version 2.7.2
10:55:29 PM: Started restoring cached go cache
10:55:29 PM: Finished restoring cached go cache
10:55:30 PM: go version go1.19.13 linux/amd64
10:55:30 PM: Using PHP version 8.0
10:55:31 PM: v18.19.0 is already installed.
10:55:32 PM: Now using node v18.19.0 (npm v10.2.3)
10:55:32 PM: Enabling Node.js Corepack
10:55:32 PM: Started restoring cached build plugins
10:55:32 PM: Finished restoring cached build plugins
10:55:32 PM: Started restoring cached corepack dependencies
10:55:32 PM: Finished restoring cached corepack dependencies
10:55:32 PM: No npm workspaces detected
10:55:32 PM: Started restoring cached node modules
10:55:32 PM: Finished restoring cached node modules
10:55:32 PM: Installing npm packages using npm version 10.2.3
10:55:37 PM: npm WARN deprecated rollup-plugin-terser@7.0.2: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-terser
10:55:37 PM: npm WARN deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead
10:55:38 PM: npm WARN deprecated workbox-cacheable-response@6.6.0: workbox-background-sync@6.6.0
10:55:53 PM: added 867 packages, and audited 868 packages in 20s
10:55:53 PM: 152 packages are looking for funding
10:55:53 PM:   run `npm fund` for details
10:55:53 PM: 1 moderate severity vulnerability
10:55:53 PM: To address all issues, run:
10:55:53 PM:   npm audit fix
10:55:53 PM: Run `npm audit` for details.
10:55:53 PM: npm packages installed
10:55:53 PM: Successfully installed dependencies
10:55:53 PM: Starting build script
10:55:54 PM: Detected 1 framework(s)
10:55:54 PM: "next" at version "13.5.5"
10:55:54 PM: Section completed: initializing
10:55:55 PM: ​
10:55:55 PM: Netlify Build                                                 
10:55:55 PM: ────────────────────────────────────────────────────────────────
10:55:55 PM: ​
10:55:55 PM: ❯ Version
10:55:55 PM:   @netlify/build 29.32.4
10:55:55 PM: ​
10:55:55 PM: ❯ Flags
10:55:55 PM:   baseRelDir: true
10:55:55 PM:   buildId: 65b53563391a75b90e94e8b0
10:55:55 PM:   deployId: 65b53563391a75b90e94e8b2
10:55:55 PM: ​
10:55:55 PM: ❯ Current directory
10:55:55 PM:   /opt/build/repo
10:55:55 PM: ​
10:55:55 PM: ❯ Config file
10:55:55 PM:   No config file was defined: using default values.
10:55:55 PM: ​
10:55:55 PM: ❯ Context
10:55:55 PM:   production
10:55:55 PM: ​
10:55:55 PM: ❯ Installing plugins
10:55:55 PM:    - @netlify/plugin-nextjs@4.41.3
10:56:05 PM: ​
10:56:05 PM: ❯ Using Next.js Runtime - v4.41.3
10:56:06 PM: ​
10:56:06 PM: @netlify/plugin-nextjs (onPreBuild event)                     
10:56:06 PM: ────────────────────────────────────────────────────────────────
10:56:06 PM: ​
10:56:06 PM: No Next.js cache to restore.
10:56:06 PM: Netlify configuration property "build.environment.NEXT_PRIVATE_TARGET" value changed.
10:56:06 PM: ​
10:56:06 PM: (@netlify/plugin-nextjs onPreBuild completed in 56ms)
10:56:06 PM: ​
10:56:06 PM: Build command from Netlify app                                
10:56:06 PM: ────────────────────────────────────────────────────────────────
10:56:06 PM: ​
10:56:06 PM: $ npm run build
10:56:07 PM: > moopa@4.3.0 build
10:56:07 PM: > next build
10:56:08 PM: ⚠ No build cache found. Please configure build caching for faster rebuilds. Read more: https://nextjs.org/docs/messages/no-cache
10:56:08 PM:    Linting and checking validity of types ...
10:56:10 PM: ./components/anime/mobile/topSection.js
10:56:10 PM: 59:11  Warning: Using `<img>` could result in slower LCP and higher bandwidth. Consider using `<Image />` from `next/image` to automatically optimize images. This may incur additional usage or cost from your provider. See: https://nextjs.org/docs/messages/no-img-element  @next/next/no-img-element
10:56:10 PM: ./components/watch/primary/details.js
10:56:10 PM: 43:13  Warning: Using `<img>` could result in slower LCP and higher bandwidth. Consider using `<Image />` from `next/image` to automatically optimize images. This may incur additional usage or cost from your provider. See: https://nextjs.org/docs/messages/no-img-element  @next/next/no-img-element
10:56:10 PM: info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules
10:56:10 PM:    Creating an optimized production build ...
10:56:10 PM: > [PWA] Compile server
10:56:10 PM: > [PWA] Compile server
10:56:10 PM: > [PWA] Compile client (static)
10:56:10 PM: > [PWA] Auto register service worker with: /opt/build/repo/node_modules/next-pwa/register.js
10:56:10 PM: > [PWA] Service worker: /opt/build/repo/public/sw.js
10:56:10 PM: > [PWA]   url: /sw.js
10:56:10 PM: > [PWA]   scope: /
10:56:10 PM: > [PWA] Fallback to precache routes when fetch failed from cache or network:
10:56:10 PM: > [PWA]   document (page): /_offline
10:56:17 PM: <w> [webpack.cache.PackFileCacheStrategy] Serializing big strings (836kiB) impacts deserialization performance (consider using Buffer instead and decode when needed)
10:56:26 PM:  ✓ Compiled successfully
10:56:26 PM:    Collecting page data ...
10:56:29 PM:  ArtPlayer  5.0.9  https://artplayer.org
10:56:30 PM: REDIS_URL is not defined. Redis caching will be disabled.
10:56:30 PM: REDIS_URL is not defined. Redis caching will be disabled.
10:56:30 PM: REDIS_URL is not defined. Redis caching will be disabled.
10:56:30 PM: REDIS_URL is not defined. Redis caching will be disabled.
10:56:30 PM: Prisma has detected that this project was built on Netlify CI, which caches dependencies. This leads to an outdated Prisma Client because Prisma"s auto-generation isn"t triggered. To fix this, make sure to run the `prisma generate` command during the build process.
10:56:30 PM: Learn how: https://pris.ly/d/netlify-build
10:56:30 PM: PrismaClientInitializationError: Prisma has detected that this project was built on Netlify CI, which caches dependencies. This leads to an outdated Prisma Client because Prisma"s auto-generation isn"t triggered. To fix this, make sure to run the `prisma generate` command during the build process.
10:56:30 PM: Learn how: https://pris.ly/d/netlify-build
10:56:30 PM:     at pa (/opt/build/repo/node_modules/@prisma/client/runtime/library.js:36:69)
10:56:30 PM:     at new t (/opt/build/repo/node_modules/@prisma/client/runtime/library.js:128:2640)
10:56:30 PM:     at 9422 (/opt/build/repo/.next/server/chunks/9422.js:1:194)
10:56:30 PM:     at __webpack_require__ (/opt/build/repo/.next/server/webpack-runtime.js:1:146)
10:56:30 PM:     at /opt/build/repo/.next/server/pages/en/anime/watch/[...info].js:1:36585
10:56:30 PM:     at __webpack_require__.a (/opt/build/repo/.next/server/webpack-runtime.js:1:991)
10:56:30 PM:     at 944 (/opt/build/repo/.next/server/pages/en/anime/watch/[...info].js:1:36383)
10:56:30 PM:     at __webpack_require__ (/opt/build/repo/.next/server/webpack-runtime.js:1:146)
10:56:30 PM:     at /opt/build/repo/.next/server/pages/en/anime/watch/[...info].js:1:470
10:56:30 PM:     at __webpack_require__.a (/opt/build/repo/.next/server/webpack-runtime.js:1:991) {
10:56:30 PM:   clientVersion: "5.3.1",
10:56:30 PM:   errorCode: undefined
10:56:30 PM: }
10:56:30 PM: > Build error occurred
10:56:30 PM: Error: Failed to collect page data for /en/anime/watch/[...info]
10:56:30 PM:     at /opt/build/repo/node_modules/next/dist/build/utils.js:1171:15 {
10:56:30 PM:   type: "Error"
10:56:30 PM: }
10:56:30 PM: ​
10:56:30 PM: "build.command" failed                                        
10:56:30 PM: ────────────────────────────────────────────────────────────────
10:56:30 PM: ​
10:56:30 PM:   Error message
10:56:30 PM:   Command failed with exit code 1: npm run build (https://ntl.fyi/exit-code-1)
10:56:30 PM: ​
10:56:30 PM:   Error location
10:56:30 PM:   In Build command from Netlify app:
10:56:30 PM:   npm run build
10:56:30 PM: ​
10:56:30 PM:   Resolved config
10:56:30 PM:   build:
10:56:30 PM:     command: npm run build
10:56:30 PM:     commandOrigin: ui
10:56:30 PM:     environment:
10:56:30 PM:       - NEXT_PRIVATE_TARGET
10:56:30 PM:     publish: /opt/build/repo/.next
10:56:30 PM:     publishOrigin: ui
10:56:30 PM:   plugins:
10:56:30 PM:     - inputs: {}
10:56:30 PM:       origin: ui
10:56:30 PM:       package: "@netlify/plugin-nextjs"
10:56:31 PM: Failed during stage "building site": Build script returned non-zero exit code: 2
10:56:31 PM: Build failed due to a user error: Build script returned non-zero exit code: 2
10:56:31 PM: Failing build: Failed to build site
10:56:31 PM: Finished processing build request in 1m5.421s

**Comment by Naiml007** [comment]
![image](https://github.com/Ani-Moopa/Moopa/assets/90306726/cb71c43e-e81f-4154-9b28-d5a88cc32a15)

**Comment by Artrix9095** [comment]
From what I can see it looks to be a problem with your prisma schema generation. Did you make sure to set your DATABASE_URL in your Environment variables tab?

**Comment by Naiml007** [comment]
> From what I can see it looks to be a problem with your prisma schema generation. Did you make sure to set your DATABASE_URL in your Environment variables tab?

yeah its in env

**Comment by Naiml007** [comment]
![Screenshot 2024-01-28 000545](https://github.com/Ani-Moopa/Moopa/assets/90306726/7194be6e-8f6a-4ba1-b52f-53824ebfcad8)

**Comment by DevanAbinaya** [comment]
looks like you haven't run `prisma generate` before building the app. Make sure to run it first by modifying the `build` script inside package.json like so:
```
"build": "npx prisma migrate deploy && npx prisma generate && next build"
```
after that redeploy the app, and see if it works or not.

**Comment by Naiml007** [comment]
I deployed using your build command: "build": "npx prisma migrate deploy && npx prisma generate && next build." After deploying, I changed this line to "build": "next build," but I'm still encountering the Internal Server Error both times.

**Comment by Naiml007** [comment]
Build settings
![Screenshot_2024-02-02-00-28-59-040_com android chrome](https://github.com/Ani-Moopa/Moopa/assets/90306726/6a97c226-a1cb-4f64-ab67-7c0583f871fa)

**Comment by DevanAbinaya** [comment]
hmm why dont you deploy it on vercel?

**Comment by Naiml007** [comment]
> hmm why dont you deploy it on vercel?

I exceeded my free limit on Vercel.

**Comment by DevanAbinaya** [comment]
can't be deployed on netlify
