### ISSUE TITLE
English Dub

### ISSUE THREAD

**Issue by jimmy-c-n** [Ani-Moopa/Moopa#24]
Hey,

This is amazing. But just wondering if it would be possible to provide the option to switch to English dubs on seasons/series that support it? I would assume it is just an additional request via the api when called, and a small amount of additional code to switch out the video on the site? Though, the API on the other hand might not support it. Regardless, you've done amazing work btw.

**Comment by DevanAbinaya** [comment]
Absolutely! I'll let you know once I get it done, or you can join my discord server for future updates. Even though I haven't done much lately cause I've been working on another project atm so you wouldn't see much updates from me right now. But of course I'll try my best to add this feature soon.

Thank you for your suggestion! :)

**Comment by jimmy-c-n** [comment]
Ah awesome! Thanks for the response. No worries at all, after-all, you are doing this as a passion project. So if/when you get time, that would be sweet.

**Comment by DevanAbinaya** [comment]
hi, dub options have been added to the latest version, I'm really sorry to make you wait this long @jimmy-c-n <3

**Comment by jimmy-c-n** [comment]
Awesome! No worries at all :) Thanks so much.
