### ISSUE TITLE
https://ruka.moopa.live/api/schedules not working.

### ISSUE THREAD

**Issue by IrzK** [Ani-Moopa/Moopa#29]
**Describe the bug**
https://ruka.moopa.live/api/schedule is down (host is down)

**Expected behavior**
The website to be up.

**Screenshots**
![image](https://github.com/Ani-Moopa/Moopa/assets/140863275/44f4cc3b-4492-4034-a634-a7e5ca78805b)

**Desktop (please complete the following information):**
 - OS: Chromebook
 - Browser: Chrome 
 - ChromeOS Version: Version 114.0.5735.239 (Official Build) (64-bit)

**Possible Solution**
can you host the web back up again?

**Comment by DevanAbinaya** [comment]
I change the sub domain to aka.moopa.live
