### ISSUE TITLE
Subtitle 

### ISSUE THREAD

**Issue by olimpa** [Ani-Moopa/Moopa#30]
**Is your feature request related to a problem? Please describe.**
Yes, my feature request is related to a problem. The problem is that many people struggle to understand and follow video content, especially those who are deaf or hard of hearing, have different language proficiency levels, or learn better through visual aids. This can lead to a lack of engagement, comprehension, and inclusivity.

**Describe the solution you'd like**
I would like to request a feature that allows users to access a variety of subtitles in different languages for videos on the platform. This feature would enable users to choose from a range of subtitles that cater to their individual needs, preferences, and language proficiency levels. The subtitles could be available in multiple languages, including English, Spanish, French, Chinese, Arabic, and others.

**Describe alternatives you've considered**
Alternative solutions that I have considered include using automatic captioning tools, which can provide subtitles in various languages. However, these tools often produce inaccurate or incomplete subtitles, particularly for non-English languages. Another alternative is to rely on community contributions, where volunteers create and submit subtitles in different languages. While this approach has worked for some platforms, it may not be feasible or reliable for all communities, especially those with limited resources or linguistic diversity.

**Additional context**
Na

**Comment by chitrakshbotwala** [comment]
This can be done but it would take a ton of time to complete , there are more than 100 languages and even if we consider the main languages say 25 , it would still be hard to find APIs that provide subtitles in these languages and also if we use auto subtitling tools in my opinion these tools wouldn't generate accurate subs for Japanese ( cause they can't even generate accurate subs for english well) in my opinion this would take a lot of time and is a unnecessary feature atm as dub has already been added and most people who watch anime would understand english
