### ISSUE TITLE
Hope to add a function to continue watching

### ISSUE THREAD

**Issue by blogclub** [Ani-Moopa/Moopa#38]
Hope to add a function to continue watching, like this
![截屏2023-08-08 10 07 19](https://github.com/Ani-Moopa/Moopa/assets/72648772/abce0a09-6fb6-44b1-aa9e-68f443339636)

**Comment by DevanAbinaya** [comment]
We're currently working on it, thank you for the suggestion <3

**Comment by blogclub** [comment]
> We're currently working on it, thank you for the suggestion <3

Thanks a lot, as I'm not logged in, I hope it's browser based viewing history, thanks again

**Comment by DevanAbinaya** [comment]
Hi, I've added recently watched feature to the latest version, it works both local and login. I hope you liked it :)
If you have anything that should be added next feel free to share it with me.

![image](https://github.com/Ani-Moopa/Moopa/assets/97084324/7a10c150-a563-4fa2-a320-b595ab451644)
