### ISSUE TITLE
[Site Request] Marin.moe

### ISSUE THREAD

**Issue by clean203** [Ani-Moopa/Moopa#43]
**Is your feature request related to a problem? Please describe.**
Adding marin.moe

**Describe the solution you'd like**
Consumet already has support for marin.

**Describe alternatives you've considered**
🤷🏼 

**Additional context**
🤷🏼

**Comment by Eltik** [comment]
Unfortunately Marin has shut down :( This would've been a good idea though

**Comment by clean203** [comment]
Oof yeah :(
Since Marin is dead in the water, i wanna tack on(not a site but seems to be an extension?) Yomiroll to this issue. Yomiroll seems to be a crunchyroll scraper that's working really well(atleast from what I've seen in projects like aniyomi).
