### ISSUE TITLE
Thumbnail review

### ISSUE THREAD

**Issue by Mathe2005** [Ani-Moopa/Moopa#46]
This feature would be great![Screenshot_2023-08-09-18-49-29-244_com.android.chrome-edit.jpg](https://github.com/Ani-Moopa/Moopa/assets/62605025/6c0eef72-a80c-4df5-9434-b2ef7354eaa3)

**Comment by chitrakshbotwala** [comment]
Surely later some day , rn we're going working on a lot of stuff and give us some time we already have plans of adding something like this. Thankyou for the suggestion though much appreciated:)

**Comment by DevanAbinaya** [comment]
I'm afraid that this feature would be impossible to add for the current player, since ArtPlayer still doesn't support sprite vtt thumbnail.
