### ISSUE TITLE
Found a bug, the viewing progress is not displayed here

### ISSUE THREAD

**Issue by blogclub** [Ani-Moopa/Moopa#47]
Found a bug, the viewing progress is not displayed here

![截屏2023-08-10 09 23 29](https://github.com/Ani-Moopa/Moopa/assets/72648772/4424f53c-87e1-4863-a0d8-340f88a04781)

![截屏2023-08-10 09 31 11](https://github.com/Ani-Moopa/Moopa/assets/72648772/845abe3a-1380-4afb-b0ec-8f7a31393c4b)

**Comment by chitrakshbotwala** [comment]
Working on that give us some time ;), thankyou for letting us know about the issue.

**Comment by DevanAbinaya** [comment]
It's fixed now, thanks for reporting this :)
