### ISSUE TITLE
Some suggestions for playing pages and players

### ISSUE THREAD

**Issue by blogclub** [Ani-Moopa/Moopa#50]
For personal aesthetics, this may be more aesthetically pleasing：

![Untitled2](https://github.com/Ani-Moopa/Moopa/assets/72648772/1bba3c56-d72e-49df-800a-744129f05177)

**Comment by chitrakshbotwala** [comment]
Will surely work on this after sometime right now we're working the watch2gether feature , these are great hi suggestions thankyou for this and the fabulous explanation of your suggestion 😊

**Comment by blogclub** [comment]
> Will surely work on this after sometime right now we're working the watch2gether feature , these are great hi suggestions thankyou for this and the fabulous explanation of your suggestion 😊

OK

**Comment by DevanAbinaya** [comment]
While this looks and works nicely on desktop, but I'm afraid this design won't work well on mobile devices. Plus, I just added a theater mode feature to the website, so changing it now would be a bummer. Thanks for your awesome suggestion though, you did a great job on the explanation 👍

**Comment by officiallerio** [comment]
@blogclub is it okay to use this design on my site? wanna ask for permissions before copying it.

**Comment by DevanAbinaya** [comment]
> > @blogclub is it okay to use this design on my site? wanna ask for permissions before copying it.
> 
> this site is made by @DevanAbinaya not blogclub my guy
> 

He meant the watch page design that's suggested by @blogclub

**Comment by chitrakshbotwala** [comment]
> > > @blogclub is it okay to use this design on my site? wanna ask for permissions before copying it.
> > 
> > 
> > this site is made by @DevanAbinaya not blogclub my guy
> 
> He meant the watch page design that's suggested by @blogclub

mah bad

**Comment by blogclub** [comment]
> @blogclub is it okay to use this design on my site? wanna ask for permissions before copying it.

Yes, is it convenient to tell me your website?

**Comment by officiallerio** [comment]
> > @blogclub is it okay to use this design on my site? wanna ask for permissions before copying it.
> 
> Yes, is it convenient to tell me your website?

I didn't do it yet. Sure, https://leriotv.xyz/. I'ts basically just like Moopa (credits to @DevanAbinaya).

**Comment by chitrakshbotwala** [comment]
this is not  a place to talk you guys may continue your chat on our official discord server , link on the site or on the readme 
ill give it to you here too https://discord.gg/APFCnj9fna

**Comment by blogclub** [comment]
> this is not a place to talk you guys may continue your chat on our official discord server , link on the site or on the readme
> ill give it to you here too https://discord.gg/APFCnj9fna

OK
