### ISSUE TITLE
Releasing animes have missing dub

### ISSUE THREAD

**Issue by sbwgg** [Ani-Moopa/Moopa#56]
**Describe the bug**
Animes that are still releasing don't have dub but it should be available.

**To Reproduce**
1. Go to any releasing anime with dub
2. Click on 'dub button'

**Expected behavior**
It should show dub 

**Screenshots**
Example anime 
![image](https://github.com/Ani-Moopa/Moopa/assets/82095317/45ef4b25-60fe-4faa-8959-7358e147acdd)
![image](https://github.com/Ani-Moopa/Moopa/assets/82095317/e3ab9171-25bd-4e36-bb64-c79ee5b3994a)

**Comment by DevanAbinaya** [comment]
Thank you for reporting this bug, but the second image you're showing is 9anime, which is not yet supported on our site. I'll add it soon.

**Comment by DevanAbinaya** [comment]
Fixed!
