### ISSUE TITLE
[Enhancements] Some Improvement on Continue Watch

### ISSUE THREAD

**Issue by pookiewx** [Ani-Moopa/Moopa#58]
## What is the feature you'd like?

Can you put the option to delete for one full air anime completely for one click. and all so when I play next episode the full screen change. can you change to the full screen when I play the next episode. 

## Why do you think this feature would be useful?

-

## Are there any alternatives you've considered?

-

## Additional context

-

**Comment by DevanAbinaya** [comment]
Change your title with the correct format, and fill in the questions instead of writing all your descriptions on the title, if you didn't follow the rules I'll close this issue, thank you.

**Comment by pookiewx** [comment]
done

**Comment by DevanAbinaya** [comment]
see how I did here #54

**Comment by pookiewx** [comment]
So i hava to  put like that

**Comment by pookiewx** [comment]
Do you guys almost done? The fixing issues

**Comment by DevanAbinaya** [comment]
I'm sorry but due to some player limitations I can't really do anything about the auto play full screen issue, but the features for deleting one full anime will be added later this week

**Comment by pookiewx** [comment]
Okay 👍

**Comment by DevanAbinaya** [comment]
done
