### ISSUE TITLE
Rich Presence

### ISSUE THREAD

**Issue by Mathe2005** [Ani-Moopa/Moopa#59]
![image](https://github.com/Ani-Moopa/Moopa/assets/62605025/29b6bfc4-faf7-433e-9a5b-4e3c2dea0683)
when i host rich presence on my local machine and load presence from extension it stucks when i viewing anime where title should be says getting data and stucks there.

**Comment by DevanAbinaya** [comment]
Premid is indeed a bit buggy, my suggestion for you is to reload the premid app. also that would be premid's bug not moopa, so I wouldn't support any bugs related to premid here, thank you.
