### ISSUE TITLE
[Bug] Tennis no Ouji-sama dub source are not wotking for sone reasons.

### ISSUE THREAD

**Issue by pookiewx** [Ani-Moopa/Moopa#60]
![Screenshot_20230821_193441_Samsung Internet](https://github.com/Ani-Moopa/Moopa/assets/142195419/5fcfd133-ce40-4d0b-82e2-833cbcca2844)
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Possible Solution**
If you have any ideas on how to solve the issue, please describe them here.

**Comment by DevanAbinaya** [comment]
There's more than one providers for a reason.

![Screenshot_20230822-094753_Chrome.png](https://github.com/Ani-Moopa/Moopa/assets/97084324/50a749a1-2993-4c9c-9626-d5dd100c8ef6)

**Comment by pookiewx** [comment]
can you put back the gogoanime become zoro.to have some dub animes is missing
