### ISSUE TITLE
[Bug] Your Title thay are some dub animes is missing 

### ISSUE THREAD

**Issue by pookiewx** [Ani-Moopa/Moopa#61]
![Screenshot_20230822_004526_Samsung Internet](https://github.com/Ani-Moopa/Moopa/assets/142195419/5da936c1-ee54-4f64-bf2d-722f67e76fa1)
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Possible Solution**
If you have any ideas on how to solve the issue, please describe them here.

**Comment by chitrakshbotwala** [comment]
Will be fixed pls wait
