### ISSUE TITLE
[Bug] BLEACH anime not working

### ISSUE THREAD

**Issue by Ash69123** [Ani-Moopa/Moopa#62]
Bug

1. Go to BLEACH anime 
2. See error "Anime is not available"

Expected behavior
The anime should load 

Screenshots
![image](https://github.com/Ani-Moopa/Moopa/assets/127380679/b2cae58c-b4a6-4ba9-96d0-1e3a7f562574)

Desktop
 - OS-Windows 11
 - Browser-Opera Gx
 - Version  101.0.4843.55

Additional context
Only happens for This specific anime "BLEACH" as far as i know

Possible Solution
None

**Comment by chitrakshbotwala** [comment]
Consumet issue will try to fix though
