### ISSUE TITLE
[Live Search] Add Live Search Feature

### ISSUE THREAD

**Issue by devachandru** [Ani-Moopa/Moopa#63]
1. What is the feature you'd like?
I hope you know about the Live Search feature.

2. Why do you think this feature would be helpful?
This feature would be helpful in navigating anime easily. 

![Screenshot 2023-08-23 150320](https://github.com/Ani-Moopa/Moopa/assets/114492150/7f8769e3-3960-43d1-8d17-76fd315c942f)

**Comment by chitrakshbotwala** [comment]
We have a lot of bugs to fix rn so this mind be added but not soon , pls be patient

**Comment by DevanAbinaya** [comment]
Hi, I've added your suggestion, now you can search anime/manga by pressing `ctrl` + `space` anywhere.
What do you think? :)

![image](https://github.com/Ani-Moopa/Moopa/assets/97084324/7dc7538d-83d3-47e6-9636-b0bc0dc61e93)

**Comment by chitrakshbotwala** [comment]
Closing the issue as solved this thread can again be refered through discord or the participants can access it through their mails

**Comment by devachandru** [comment]
Nice one bro 👍
