### ISSUE TITLE
[Bug] Hanma Baki Season 2 are not working

### ISSUE THREAD

**Issue by pookiewx** [Ani-Moopa/Moopa#64]
![Screenshot_20230825_172456_Samsung Internet](https://github.com/Ani-Moopa/Moopa/assets/142195419/d1dd8720-6949-4e7b-b11d-a5c13962566a)
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Possible Solution**
If you have any ideas on how to solve the issue, please describe them here.

**Comment by chitrakshbotwala** [comment]
Will be fixed anity or consumet issue please be patient

**Comment by pookiewx** [comment]
Please do fast as you can. Because I'm Planning to watch  is anime

**Comment by DevanAbinaya** [comment]
Should be working now, sorry for the inconveniences.
