### ISSUE TITLE
[Bug] Am I Actually the Strongest a anime dub are not Working

### ISSUE THREAD

**Issue by pookiewx** [Ani-Moopa/Moopa#66]
![Screenshot_20230831_171228_Samsung Internet](https://github.com/Ani-Moopa/Moopa/assets/142195419/15b15286-fcd5-4fe7-ba96-eb817e4a9ac7)
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Possible Solution**
If you have any ideas on how to solve the issue, please describe them here.

**Comment by DevanAbinaya** [comment]
Looks like the API doesn't return the episodes, I'll look into it

**Comment by pookiewx** [comment]
Thanks bro

**Comment by DevanAbinaya** [comment]
It's back
