### ISSUE TITLE
[Enhancements] I like you to update the new animes a bit faster on moopa.live.

### ISSUE THREAD

**Issue by pookiewx** [Ani-Moopa/Moopa#67]
## What is the feature you'd like?

Please describe the feature you'd like to see in this project.

## Why do you think this feature would be useful?

Please explain why you think this feature would be useful.

## Are there any alternatives you've considered?

Please describe any alternative solutions or features you've considered.

**Comment by DevanAbinaya** [comment]
Autoplay next isn't working? Can you reproduce the problem?

**Comment by DevanAbinaya** [comment]
issue is answered and will be marked as solved
