### ISSUE TITLE
[Bug] lThe auto play Button is not working 

### ISSUE THREAD

**Issue by pookiewx** [Ani-Moopa/Moopa#68]
**Describe the bug**

**To Reproduce**

**Expected behavior**
A clear and concise description of what you expected to happen. When I play next episode I Hava to go back and play next episode 

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Possible Solution**
If you have any ideas on how to solve the issue, please describe them here.

**Comment by DevanAbinaya** [comment]
I need details on the bugs, the more details you gave the faster it get solved

**Comment by pookiewx** [comment]
When I play the next episode it doesn't play So I switch to full screen and click the next station button

**Comment by DevanAbinaya** [comment]
Can you record or send a screenshot how it happen?

**Comment by pookiewx** [comment]
Is the Screen recording

**Comment by pookiewx** [comment]
This is the screen according

https://github.com/Ani-Moopa/Moopa/assets/142195419/90e17efb-4422-42d1-8547-3da4a24e0b7f

**Comment by DevanAbinaya** [comment]
You mean this button? It's for seeking the video 5s

![Screenshot_20230901-105932_Chrome.png](https://github.com/Ani-Moopa/Moopa/assets/97084324/1c284b00-4ad4-44a5-a906-0542575dcb19)

**Comment by pookiewx** [comment]
Do you see the button saying  Auto button I am talking about that So When I play The Next Episode? I have to Click the play button.it don't play automatically

**Comment by pookiewx** [comment]
https://github.com/Ani-Moopa/Moopa/assets/142195419/c38c777a-8fe8-49c1-9fc9-554bac770c0f

Do you see? It's play automatically that I'm talking about.

**Comment by pookiewx** [comment]
Do you see? It's play automatically When I go to next episode

Uploading Screen_Recording_20230831_211453_Samsung Internet.mp4…

**Comment by pookiewx** [comment]
Do you see? It's play automatically that I'm talking about.

https://github.com/Ani-Moopa/Moopa/assets/142195419/c9a20ee6-ecc7-4b6b-96f2-08ad06dcd652

**Comment by pookiewx** [comment]
Hello

**Comment by chitrakshbotwala** [comment]
Please don't chat on github issues pookie use the discord server for that

**Comment by pookiewx** [comment]
> Please don't chat on github issues pookie use the discord server for that

What do you mean by that This is the place for put issues right so
