### ISSUE TITLE
[Bug] Your Title Here

### ISSUE THREAD

**Issue by InstaTechHD** [Ani-Moopa/Moopa#80]
**Describe the bug**

**To Reproduce**
1. Go to any anime (Tested with jobless reincarnation *Mushoku Tensei: Jobless Reincarnation Season 2*
2. Click on Dub
3. Scroll down to Click play now
4. See error (Shows Once in a while)

**Expected behavior**
Expected to see the video to play but it threw a 500 error

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Edge
 - Version NA/Latest

**Comment by DevanAbinaya** [comment]
I hope it fixed now, please check again.

**Comment by DevanAbinaya** [comment]
inactive issue
