### ISSUE TITLE
[Bug] Login isn't working after the update

### ISSUE THREAD

**Issue by xenonslime** [Ani-Moopa/Moopa#81]
**Describe the bug**
Can't login. It always says Log In the navigation bar. And when I try to login it doesn't work.

**To Reproduce**
1. Go to 'moopa'
2. Click on 'login'
4. Nothing happens/can't login

**Expected behavior**
it would login to my anilist account and show me things like recently watched and my watchlist

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser chrome
 - Version 117.0.5938.92

**Additional context**
It worked before the update..

**Comment by DevanAbinaya** [comment]
Try deleting browser cache and try login again

**Comment by DevanAbinaya** [comment]
try this,

1. open your dev tools and go to `application`:
![image](https://github.com/Ani-Moopa/Moopa/assets/97084324/bd68886c-5e5b-490d-82e8-3ffc4c8d77d4)

2. click on unregister button, then refresh the page:
![image](https://github.com/Ani-Moopa/Moopa/assets/97084324/1e8d835c-2f65-4504-bdef-82abb7e09a9b)

**Comment by DevanAbinaya** [comment]
hmm, this is weird

**Comment by DevanAbinaya** [comment]
what if you click the update button?

**Comment by DevanAbinaya** [comment]
clear cache and cookies and restart browser, and hope it works 🤞🏼
