### ISSUE TITLE
The icon to open the video player appears small on Android, making it almost impossible to click.

### ISSUE THREAD

**Issue by chative-phuc** [Ani-Moopa/Moopa#87]
When using your app in my mobile browser, I noticed that the icon to enlarge the video player is too small, making it difficult for me to click. I have recently started using your app, so it would be great if you could address this issue. :smile: 

![369498096_339318861917182_5939424365987754072_n](https://github.com/Ani-Moopa/Moopa/assets/128776850/be05a09c-6ede-4691-aedc-a4159e8bb888)
**Smartphone (please complete the following information):**
 - Device: Red magic 7
 - OS: Android 12
 - Browser : Braver

**Additional context**

**Possible Solution**
If you have any ideas on how to solve the issue, please describe them here.

**Comment by DevanAbinaya** [comment]
Hi, I'm really sorry to hear that. The only thing I can suggest to you right now is to change your screen display size to small/smaller, in the meantime I will try to find and fix the problem.
