### ISSUE TITLE
[Issue in] Playback Speed

### ISSUE THREAD

**Issue by shrkwt** [Ani-Moopa/Moopa#88]
Add playback speed option for mobile devices and if possible then add 1.15x speed.
Currently not having the right device to create a pull request.

**Comment by wyMinLwin** [comment]
@shrkwt  
if you want to the playback speed in video's setting let me try it out.
You can give me the playback speed options

**Comment by shrkwt** [comment]
Would be good with all the common options,
`Normal` `1.15x` `1.25x` `1.50x` `1.75x` `2.00x`
Also, I think the options are provided by default by the video player used in the website, it may just require slight changes.

**Comment by shrkwt** [comment]
*I know that this option is there*
But look in my phone,

![Screenshot_2023-10-17-10-57-00-752_com android chrome](https://github.com/Ani-Moopa/Moopa/assets/77541532/7d41f427-b926-4ebf-b867-84e626370bb6)

It's not showing up.

**Comment by DevanAbinaya** [comment]
done
