### ISSUE TITLE
Double tap to seek forward, backward

### ISSUE THREAD

**Issue by rakibdev** [Ani-Moopa/Moopa#96]
## What is the feature you'd like?

Like YouTube. It also shows nice ripple effect when clicked.

## Why do you think this feature would be useful?

Please explain why you think this feature would be useful.

## Are there any alternatives you've considered?

Please describe any alternative solutions or features you've considered.

**Comment by DevanAbinaya** [comment]
that would be a great feature, but since it's Artplayer I'm not sure I'll be able to do that. I'm not really familiar with writing player, so this might take some time to implement
