### ISSUE TITLE
[Enhancements] Play anime on the video clip front page

### ISSUE THREAD

**Issue by pookiewx** [Ani-Moopa/Moopa#97]
## What is the feature you'd like? anime plays automatically play the video clip

Please describe the feature you'd like to see in this project. add the anime video slide to the front page when I Change 

https://github.com/Ani-Moopa/Moopa/assets/142195419/5f025c09-aa78-42d3-92bf-9302b7b3caad

the anime plays automatically play the video clip can you do that please

## Why do you think this feature would be useful? To see what the anime like is show little detail 

Please explain why you think this feature would be useful. 

## Are there any alternatives you've considered?

Please describe any alternative solutions or features you've considered.

**Comment by chitrakshbotwala** [comment]
I would love if you describe the feature you request in a better way , anyways thankyou for using MOOPA

**Comment by pookiewx** [comment]
When you open the first front page,the top of the page.it is brought to the top of the trending now continue watch.  trending now When you click on each anime, the name of the anime and the photo on the side and the video on the other side are played.

**Comment by officiallerio** [comment]
i think he meant like netflix style where it plays an trailer lol.

**Comment by pookiewx** [comment]
Ya just like Netflix

**Comment by chitrakshbotwala** [comment]
I see , would try to do it soon not now though tbh

**Comment by DevanAbinaya** [comment]
this would make me rewrite/redesign the homepage which will take some time to do, so this will be on the least priority to do. it's not impossible for me to implement this but this is definitely not on my priority right now
